#ifndef LAB7_MODULES_EVENT_LISTENER_EVENT_LISTENER_H_
#define LAB7_MODULES_EVENT_LISTENER_EVENT_LISTENER_H_

#include "windows.h"

bool ListenKeyPressed(int key);

#endif //LAB7_MODULES_EVENT_LISTENER_EVENT_LISTENER_H_
